---

cors:
  allowed-origins:
    - http://localhost:8080
    - https://api.lotusforge.au
    - http://localhost
    - http://127.0.0.1:8080
  allowed-headers:
    - X-Username
    - X-API-Key
    - Content-Type
    - Authorization
    - X-User-Note
  allow-credentials: true
