---
name: Asset Categories
version: 1.1.0
table-name: asset_categories
end-point: asset/category
allow-diff: false

primary-key: cat_code

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  cat_code:
    type: string
    json: cat_code
    db-type: text
    required-on-insert: true
  asset_system:
    type: string
    json: asset_system
    db-type: text
    nullable: true
  asset_subsystem:
    type: string
    json: asset_subsystem
    db-type: text
    nullable: true
  is_active:
    type: bool
    json: is_active
    db-type: boolean
    default: "true"
  description:
    type: string
    json: description
    db-type: text
    default: ""
