---
name: Asset Data
version: 1.1.0
table-name: asset_data
end-point: asset/data
allow-diff: true
diff-comparator: asset_no

primary-key: asset_no

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  asset_id:
    type: int
    json: asset_id
    db-type: int
    nullable: true
    skip-insert: true
    include-in-diff: false
  added_date:
    type: string
    json: added_date
    db-type: text
    default: "now()"
    include-in-diff: false
  additional_details:
    type: string
    json: additional_details
    db-type: text
    default: ""
    include-in-diff: true
  asset_category:
    type: string
    json: asset_category
    db-type: text
    required-on-insert: true
    nullable: true
    include-in-diff: true
  asset_no:
    type: string
    json: asset_no
    db-type: text
    required-on-insert: true
    include-in-diff: false
  asset_status:
    type: string
    json: asset_status
    db-type: text
    default: "A"
    include-in-diff: true
  building:
    type: string
    json: building
    db-type: text
    required-on-insert: true
    nullable: true
    include-in-diff: true
  condition_rating:
    type: int
    json: condition_rating
    db-type: int
    nullable: true
    include-in-diff: true
  condition_rating_date:
    type: string
    json: condition_rating_date
    db-type: text
    nullable: true
    include-in-diff: true
  contact_id:
    type: string
    json: contact_ID
    db-type: text
    nullable: true
    include-in-diff: false
  department:
    type: string
    json: department
    db-type: text
    required-on-insert: true
    nullable: true
    include-in-diff: true
  description:
    type: string
    json: description
    db-type: text
    required-on-insert: true
    nullable: true
    include-in-diff: true
  disposal_cost:
    type: float
    json: disposal_cost
    db-type: numeric
    nullable: true
    include-in-diff: true
  disposal_date:
    type: string
    json: disposal_date
    db-type: text
    nullable: true
    include-in-diff: true
  disposal_reason:
    type: string
    json: disposal_reason
    db-type: text
    nullable: true
    include-in-diff: true
  domain:
    type: string
    json: domain
    db-type: text
    required-on-insert: true
    nullable: true
    include-in-diff: true
  finance_group_code:
    type: string
    json: finance_group_code
    db-type: text
    nullable: true
    include-in-diff: false
  floor:
    type: string
    json: floor
    db-type: text
    nullable: true
    absolute-match: true
    include-in-diff: true
  gl_asset_reference:
    type: string
    json: GL_asset_reference
    db-type: text
    nullable: true
    include-in-diff: false
  install_date:
    type: string
    json: install_date
    db-type: text
    nullable: true
    include-in-diff: true
  installation_cost:
    type: float
    json: installation_cost
    db-type: numeric
    nullable: true
    include-in-diff: true
  invoice_no:
    type: string
    json: invoice_no
    db-type: text
    nullable: true
    include-in-diff: true
  is_virtual_asset:
    type: bool
    json: is_virtual_asset
    db-type: boolean
    default: "false"
    include-in-diff: false
  label_location:
    type: string
    json: label_location
    db-type: text
    nullable: true
    include-in-diff: false
  latitude:
    type: float
    json: latitude
    db-type: numeric
    nullable: true
    include-in-diff: true
  location:
    type: string
    json: location
    db-type: text
    nullable: true
    include-in-diff: false
  longitude:
    type: float
    json: longitude
    db-type: numeric
    nullable: true
    include-in-diff: true
  make:
    type: string
    json: make
    db-type: text
    nullable: true
    include-in-diff: true
  manufacturer:
    type: string
    json: manufacturer
    db-type: text
    nullable: true
    include-in-diff: false
  model:
    type: string
    json: model
    db-type: text
    nullable: true
    include-in-diff: true
  owning_cost_center:
    type: string
    json: owning_cost_center
    db-type: text
    nullable: true
    include-in-diff: true
  purchase_cost:
    type: float
    json: purchase_cost
    db-type: numeric
    nullable: true
    include-in-diff: true
  purchase_date:
    type: string
    json: purchase_date
    db-type: text
    nullable: true
    include-in-diff: true
  purchase_order_no:
    type: string
    json: purchase_order_no
    db-type: text
    nullable: true
    include-in-diff: true
  purchasing_cost_center:
    type: string
    json: purchasing_cost_center
    db-type: text
    nullable: true
    include-in-diff: true
  rfid_tag_id:
    type: string
    json: RFID_tag_ID
    db-type: text
    nullable: true
    include-in-diff: false
  room:
    type: string
    json: room
    db-type: text
    nullable: true
    include-in-diff: true
  serial:
    type: string
    json: serial
    db-type: text
    nullable: true
    include-in-diff: true
  service_agent:
    type: string
    json: service_agent
    db-type: text
    nullable: true
    include-in-diff: false
  spare_parts:
    type: string
    json: spare_parts
    db-type: text
    nullable: true
    include-in-diff: false
  spare_parts_bin_no:
    type: string
    json: spare_parts_bin_no
    db-type: text
    nullable: true
    include-in-diff: false
  spare_parts_held:
    type: string
    json: spare_parts_held
    db-type: text
    nullable: true
    include-in-diff: false
  supplier_code:
    type: string
    json: supplier_code
    db-type: text
    nullable: true
    include-in-diff: true
  tech_manual_reference:
    type: string
    json: tech_manual_reference
    db-type: text
    nullable: true
    include-in-diff: true
  user_defined_fields:
    type: string
    json: user_defined_fields
    db-type: text
    nullable: true
    include-in-diff: false
  warranty_period:
    type: int
    json: warranty_period
    db-type: int
    default: "12"
    include-in-diff: true
  working_life:
    type: int
    json: working_life
    db-type: int
    nullable: true
    include-in-diff: true
  ownership_status:
    type: string
    json: ownership_status
    db-type: text
    default: "O"
    include-in-diff: true
  altered_date:
    type: string
    json: altered_date
    db-type: text
    default: "now()"
    include-in-diff: false
