---
name: Condition Ratings
table-name: condition_ratings
end-point: condition/rating
allow:
  GET: true
  PUT: true
  POST: true
  DELETE: false
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: false
default-where: ~
overwrite-select: ~
custon-with: ~
fields:
  condition_rating:
    type: int
    json: condition_rating
    db: condition_rating
    pk: true
    req: true
    none: ~
    diff: true
    custom-where: ~
  description:
    type: string
    json: description
    db: description
    pk: false
    req: false
    none: ""
    diff: true
    custom-where: ~
  long_description:
    type: string
    json: long_description
    db: long_description
    pk: false
    req: false
    none: ""
    diff: true
    custom-where: ~
