---
name: Asset Categories
version: 1.2.2
table-name: asset_categories
end-point: asset/category
allow-diff: false

primary-key: cat_code

end-points-allowed:
  GET: []
  PUT: []
  POST: []
  DELETE: []
  PUT-GROUP: []
  POST-GROUP: []
  DELETE-GROUP: []

fields:
  cat_code:
    type: string
    json: cat_code
    db-type: character varying(20)
    required-on-insert: true
  asset_system:
    type: string
    json: asset_system
    db-type: character varying(76)
    nullable: true
  asset_subsystem:
    type: string
    json: asset_subsystem
    db-type: character varying(76)
    nullable: true
  is_active:
    type: bool
    json: is_active
    db-type: boolean
    default: true
  description:
    type: string
    json: description
    db-type: character varying(60)
    default: ""
