---
name: Building Floor Room
version: 1.1.0
table-name: building_floor_room_combo
end-point: room
allow-diff: false

primary-key: bfroom_id

foreign-keys:
  fk_building_floor_room_bfloor:
    foreign-key-fields:
      - building
      - floor
    foreign-key-target-table: building_floor_combo
    foreign-key-target-fields:
      - building
      - floor
    foreign-key-on-update: CASCADE

unique-keys:
  uk_building_floor_room_bfroom:
    unique-key-fields:
      - building
      - floor
      - room

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  bfroom_id:
    type: int
    json: bfroom_id
    db-type: smallserial
    skip-insert: true
  building:
    type: string
    json: building
    db-type: character varying(15)
    required-on-insert: true
  floor:
    type: string
    json: floor
    db-type: character varying(4)
    required-on-insert: true
    absolute-match: true
  room:
    type: string
    json: room
    db-type: character varying(15)
    required-on-insert: true
  room_description:
    type: string
    json: room_description
    db-type: character varying(100)
    default: ""
