---
name: Building Floor
version: 1.2.0
table-name: building_floor_combo
end-point: bfloor
allow-diff: false

primary-key: bfloor_id

foreign-keys:
  fk_building_floor_building:
    foreign-key-fields:
      - building
    foreign-key-target-table: buildings
    foreign-key-target-fields:
      - building
    foreign-key-on-update: CASCADE
  fk_building_floor_floor:
    foreign-key-fields:
      - floor
    foreign-key-target-table: floors
    foreign-key-target-fields:
      - floor
    foreign-key-on-update: CASCADE

unique-keys:
  uk_building_floor_bfloor:
    unique-key-fields:
      - building
      - floor

end-points-allowed:
  GET: []
  PUT: []
  POST: []
  DELETE: []
  PUT-GROUP: []
  POST-GROUP: []
  DELETE-GROUP: []

fields:
  bfloor_id:
    type: int
    json: bfloor_id
    db-type: smallserial
    skip-insert: true
  building:
    type: string
    json: building
    db-type: character varying(15)
    required-on-insert: true
  floor:
    type: string
    json: floor
    db-type: character varying(4)
    required-on-insert: true
    absolute-match: true
  is_active:
    type: bool
    json: is_active
    db-type: boolean
    default: true
