---
name: Building
version: 1.1.0
table-name: buildings
end-point: building
allow-diff: false

primary-key: building

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  building_id:
    type: int
    json: building_id
    db-type: int
    nullable: true
    skip-insert: true
  building:
    type: string
    json: building
    db-type: text
    required-on-insert: true
  db_domain:
    type: string
    json: db_domain
    db-type: text
    required-on-insert: true
  building_description:
    type: string
    json: building_description
    db-type: text
    nullable: true
  building_address:
    type: string
    json: building_address
    db-type: text
    nullable: true
  building_suburb:
    type: string
    json: building_suburb
    db-type: text
    nullable: true
  building_state:
    type: string
    json: building_state
    db-type: text
    nullable: true
  is_active:
    type: bool
    json: is_active
    db-type: boolean
    nullable: true
