---
name: Building
table-name: buildings
end-point: building
allow-diff: false
allow:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true
fields:
  building_id:
    type: int
    json: building_id
    db: building_id
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: true
  building:
    type: string
    json: building
    db: building
    pk: true
    req: true
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  db_domain:
    type: string
    json: db_domain
    db: db_domain
    pk: false
    req: true
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  building_description:
    type: string
    json: building_description
    db: building_description
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  building_address:
    type: string
    json: building_address
    db: building_address
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  building_suburb:
    type: string
    json: building_suburb
    db: building_suburb
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  building_state:
    type: string
    json: building_state
    db: building_state
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
  is_active:
    type: bool
    json: is_active
    db: is_active
    pk: false
    req: false
    none: ~
    diff: ~
    custom-where: ~
    absolute: false
    skip-insert: false
