---
name: Department
version: 1.1.0
table-name: departments
end-point: department
allow-diff: false

primary-key: dept_code

foreign-keys:
  fk_departments_building:
    foreign-key-fields:
      - building
    foreign-key-target-table: buildings
    foreign-key-target-fields:
      - building
    foreign-key-on-update: NO ACTION
  fk_department_bfloor:
    foreign-key-fields:
      - building
      - floor
    foreign-key-target-table: building_floor_combo
    foreign-key-target-fields:
      - building
      - floor
    foreign-key-on-update: CASCADE

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  dept_id:
    type: int
    json: dept_id
    db-type: serial
    nullable: true
    skip-insert: true
  dept_code:
    type: string
    json: dept_code
    db-type: character varying(15)
    required-on-insert: true
  description:
    type: string
    json: dept_description
    db-type: character varying(200)
    default: ""
  building:
    type: string
    json: building
    db-type: character varying(15)
    nullable: true
  floor:
    type: string
    json: floor
    db-type: character varying(4)
    nullable: true
    absolute-match: true
  is_active:
    type: bool
    json: is_active
    db-type: boolean
    default: true
