---
name: Domain
version: 1.1.0
table-name: domains
end-point: domain
allow-diff: false

primary-key: domain_code

end-points-allowed:
  GET: true
  PUT: true
  POST: true
  DELETE: true
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: true

fields:
  domain_code:
    type: string
    json: domain_code
    db-type: text
    required-on-insert: true
  domain_description:
    type: string
    json: domain_description
    db-type: text
    default: ""
