---
name: Floor
table-name: floors
end-point: floor
allow-diff: false
allow:
  GET: true
  PUT: true
  POST: true
  DELETE: false
  PUT-GROUP: true
  POST-GROUP: true
  DELETE-GROUP: false
fields:
  floor_id:
    type: int
    json: floor_id
    db: floor_id
    pk: false
    req: false
    none: "DEFAULT"
    diff: ~
    custom-where: ~
    absolute: false
  floor:
    type: string
    json: floor
    db: floor
    pk: true
    req: true
    none: ~
    diff: ~
    custom-where: ~
    absolute: true
