---
name: Floor
version: 1.2.0
table-name: floors
end-point: floor
allow-diff: false

primary-key: floor_id

unique-keys:
  uk_floors_floor:
    unique-key-fields:
      - floor

end-points-allowed:
  GET: []
  PUT: []
  POST: []
  PUT-GROUP: []
  POST-GROUP: []

fields:
  floor_id:
    type: int
    json: floor_id
    db-type: smallserial
    skip-insert: true
  floor:
    type: string
    json: floor
    db-type: character varying(4)
    required-on-insert: true
    absolute-match: true
