name: Map Room Override
version: 1.0.0
table-name: map_room_overrides
end-point: map/room-override
allow-diff: false
primary-key: override_id
unique-keys:
  uk_map_room_override: { unique-key-fields: [building, floor, asset_room] }
foreign-keys:
  fk_map_room_override_bfloor:
    foreign-key-fields: [building, floor]
    foreign-key-target-table: building_floor_combo
    foreign-key-target-fields: [building, floor]
    foreign-key-on-update: CASCADE
end-points-allowed: { GET: [], PUT: [], POST: [], DELETE: [] }
fields:
  override_id:        { type: int,    db-type: serial, skip-insert: true }
  building:           { type: string, db-type: character varying(15), required-on-insert: true }
  floor:              { type: string, db-type: character varying(4),  required-on-insert: true, absolute-match: true }
  asset_room:         { type: string, db-type: character varying(15), required-on-insert: true }
  geojson_room_code:  { type: string, db-type: character varying(15), required-on-insert: true }
  note:               { type: string, db-type: character varying(200), nullable: true }
  created_by:         { type: string, db-type: character varying(50),  nullable: true }
  created_at:         { type: string, db-type: timestamptz, db-default: now(), skip-insert: true }
