---

name: mh-locations
version: 1.2.0
table-name: mh_locations
end-point: locations
primary-key: location
end-points-allowed:
  GET: []
  POST: []
  PUT: []
  DELETE: []
  PUT-GROUP: []
  POST-GROUP: []
  DELETE-GROUP: []
fields:
  location:
    type: string
    db-type: character varying(40)
    json: location
    json-alias:
      - mh_location

  
